name: MumbleChat
version: 1.6.4
main: net.muttsworld.mumblechat.MumbleChat
depend: [Vault]
author: cindy_k
authors: [net_creator]
description: Chat with Channels (1.6.4 level)
website: www.minecats.com
commands:
    mute:
        usage: /mute [player] [channel]
        aliases: [mp]
        description: Mute player in a channel so they cannot talk.
        permission-message: You don't have <permission>
    chmute:
        usage: /chmute [player] [channel]
        aliases: [cmp]
        description: Mute player in a channel so they cannot talk.
        permission-message: You don't have <permission>
    unmute:
        usage: /unmute [player] [channel]
        aliases: [ump]
        description: Unmute player in a channel so they can talk again.
        permission-message: You don't have <permission>
    chunmute:
       usage: /unmute [player] [channel]
       aliases: [ump]
       description: Unmute player in a channel so they can talk again.
       permission-message: You don't have <permission>
    chforce:
       usage: /chforce [in/out] [player] [channel]
       aliases: [chf]
       description: Force a player in or out of a channel.
       permission-message: You don't have <permission>
    tell:
        usage: /tell [player] [msg]
        description: Send message to player
        permission-message: You don't have <permission>
    reply:
        usage: /reply [msg]
        aliases: [mr]
        description: Send message to player you last sent a tell to
        permission-message: You don't have <permission>
    chignore:
        usage: /chignore [player] or /chignore ? for more information
        aliases: [cig]
        description: This allows you to prevent a player from sending you a tell /chignore ? for more info
        permission-message: You don't have <permission>
    whisper:
        usage: /whisper [player] [msg]
        aliases: [w]
        description: Send message to player
        permission-message: You don't have <permission>
    channel:
        usage: /channel [channelname]
        aliases: [ch]
        description: Allows players to add the ability to listen to the channel
        permission-message: You don't have <permission>
    leave:
        usage: /leave [channelname]
        aliases: [lev]
        description: Allows players to leave listening to a channel
        permission-message: You don't have <permission>
    join:
        usage: /join [channelname]
        description: Allows players to join a channel
        permission-message: You don't have <permission>
    chlist:
        usage: /chlist
        aliases: [chl]
        description: Allows players to see a listing of available channels
        permission-message: You don't have <permission>
    chwho:
        usage: /chwho [channelname]
        aliases: [chw]
        description: Allows players to see a listing of who is listening on a channel
        permission-message: You don't have <permission>
    chversion:
        usage: /chversion
        description: Displays Description text for Ops
        permission-message: You don't have <permission>
    chfilter:
          usage: /chfilter [FilteredWord]
          description: Displays Filter for the given word.
          permission-message: You don't have <permission>
    chsetfilter:
          usage: /chsetfilter [FilteredWord] [Filter]
          description: Sets Filter for the given word.
          permission-message: You don't have <permission>
    chlookup:
        usage: /chlookup
        description: Displays Player Info, such as mutes and last on.
        permission-message: You don't have <permission>
    chhelp:
        usage: /chhelp
        description: Help information for users
        permission-message: You don't have <permission>
    who:
        usage: /who
        aliases: [online]
        description: Help information for users
        permission-message: You don't have <permission>
        
        
        